In [1]:
import geopandas as gpd

/Users/ncg/.local/share/virtualenvs/gvallocation-xprzTUHK/lib/python3.7/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
df = gpd.read_file('../data/riskscore/homicides.csv')
df.head(10)

,field_1,RD_NO,HOMICIDE_NO,ID,DEATH_DATE,INJURY_DATE,STREET_NO,STREET_DIRECTION_CD,STREET_NME,APT_NO,...,VICTIM_RACE,VICTIM_AGE,VICTIM_SEX,VICTIM_IR_NO,MOTIVE_DESCR,VICTIM_GANG_NAME,VICTIM_FACTION_NAME,CLEARED_I,DATE_CLEARED,geometry
0,1,K146583,88040162,9299,15-APR-88,15-APR-88,1711,S,HAMILTON AVE,NA,...,WHI,60,M,NA,OTHER,NA,NA,Y,18-APR-88,None
1,2,K146585,88040163,9300,15-APR-88,15-APR-88,1511,W,FULLERTON AVE,NA,...,WHI,35,M,285550,NARCOTICS,NA,NA,Y,21-APR-88,None
2,3,K146739,88040164,9301,15-APR-88,15-APR-88,3842,N,JANSSEN AVE,NA,...,WHI,28,M,561341,UNDETERMINED,NA,NA,N,NA,None
3,4,K146741,88040165,9302,15-APR-88,15-APR-88,3651,S,FEDERAL ST,NA,...,BLK,34,M,437915,UNDETERMINED,NA,NA,N,NA,None
4,5,M142623,89040175,9969,02-APR-89,02-APR-89,637,N,CHRISTIANA AVE,NA,...,BLK,21,M,NA,GENERAL DOMESTIC,NA,NA,Y,03-APR-89,None
5,6,M142941,89040176,9970,03-APR-89,03-APR-89,5942,S,DR MARTIN LUTHER KING JR DR,NA,...,BLK,37,M,250689,UNDETERMINED,NA,NA,N,NA,None
6,7,M142094,89040177,9971,03-APR-89,02-APR-89,4635,S,DR MARTIN LUTHER KING JR DR,NA,...,BLK,13,M,NA,THEFT (ALLEGED),NA,NA,Y,04-APR-89,None
7,8,M130220,89040178,9972,03-APR-89,25-MAR-89,748,W,DIVERSEY PKWY,NA,...,BLK,32,M,456332,UNDETERMINED,NA,NA,N,NA,None
8,9,M145820,89040179,9973,04-APR-89,04-APR-89,4327,W,18TH ST.,NA,...,BLK,37,M,231530,MONEY,NA,NA,Y,05-APR-89,None
9,10,M145967,89040180,9974,04-APR-89,04-APR-89,6058,S,UNION AVE,NA,...,BLK,29,M,510965,GENERAL DOMESTIC,NA,NA,Y,05-APR-89,None

In [24]:
type(df)

geopandas.geodataframe.GeoDataFrame

In [3]:
shapes = gpd.read_file('../data/geometries/zipcode_geometries.csv')

In [4]:
shapes = shapes.rename(columns={'the_geom':'SHAPES',
                       'ZIP': 'ZIP_CD'})

In [5]:
working_shapes = shapes[['ZIP_CD', 'SHAPES']]

In [6]:
working_shapes['ZIP_CD'] = working_shapes['ZIP_CD'].astype('object')

/Users/ncg/.local/share/virtualenvs/gvallocation-xprzTUHK/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [7]:
working_df = df[['ZIP_CD', 'ID']]

In [8]:
working_df['ZIP_CD'] = working_df['ZIP_CD'].astype('object')

/Users/ncg/.local/share/virtualenvs/gvallocation-xprzTUHK/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [9]:
working_df

      ZIP_CD     ID
0      60608   9299
1      60614   9300
2      60613   9301
3      60609   9302
4      60624   9969
...      ...    ...
24151  60623  22552
24152  60609  22575
24153  60636  22574
24154  60629  22580
24155  60621  22586

[24156 rows x 2 columns]

In [10]:
# remember: .nunique() automatically gets counts
zipcode = working_df.groupby('ZIP_CD')['ID'].nunique().sort_values(ascending=False).to_frame()

In [11]:
import pandas as pd

In [12]:
zipcode = pd.merge(zipcode, working_shapes, on='ZIP_CD')

In [13]:
zipcode

   ZIP_CD    ID                                             SHAPES
0   60624  1308  MULTIPOLYGON (((-87.70566918657467 41.86640531...
1   60609  1136  MULTIPOLYGON (((-87.6266459027657 41.830905861...
2   60623  1122  MULTIPOLYGON (((-87.69479284658739 41.83007507...
3   60651  1087  MULTIPOLYGON (((-87.70655631674127 41.89555340...
4   60644  1016  MULTIPOLYGON (((-87.73998200704422 41.86595917...
..    ...   ...                                                ...
56  60604    10  MULTIPOLYGON (((-87.63375869381524 41.87924230...
57  60606     5  MULTIPOLYGON (((-87.63397066191104 41.88752780...
58  60603     4  MULTIPOLYGON (((-87.61633485348139 41.88211174...
59  60602     4  MULTIPOLYGON (((-87.60996958016865 41.88435728...
60  60666     2  MULTIPOLYGON (((-87.8959834798129 42.005784524...

[61 rows x 3 columns]

In [14]:
zipcode = zipcode.drop(zipcode.index[0])
zipcode = zipcode.rename(columns={'ID':'Homicides'})
zipcode['Score'] = 0
zipcode.head()

  ZIP_CD  Homicides                                             SHAPES  Score
1  60609       1136  MULTIPOLYGON (((-87.6266459027657 41.830905861...      0
2  60623       1122  MULTIPOLYGON (((-87.69479284658739 41.83007507...      0
3  60651       1087  MULTIPOLYGON (((-87.70655631674127 41.89555340...      0
4  60644       1016  MULTIPOLYGON (((-87.73998200704422 41.86595917...      0
5  60628        982  MULTIPOLYGON (((-87.58514614909825 41.72160409...      0

In [15]:
def get_percentile_score(dataframe, category):
    
    fifth = int(dataframe[category].quantile(.95))
    tenth = int(dataframe[category].quantile(.90))
    twentyfifth = int(dataframe[category].quantile(.75))
    fiftieth = int(dataframe[category].quantile(.50))

    score = list()
    for index in dataframe.index:
        if dataframe[category][index] > fiftieth:
            if dataframe[category][index] > twentyfifth:
                if dataframe[category][index] > tenth:
                    if dataframe[category][index] > fifth:
                        score.append(4)
                    else:
                        score.append(3)
                else:
                    score.append(2)
            else:
                score.append(1)
        else:
            score.append(0)
    return score

In [16]:
homicide_scores = get_percentile_score(zipcode, 'Homicides')
# shooting_scores = get_percentile_score(zipcode, 'Shootings')

In [17]:
def add_scores(dataframe, *argv):
    for arg in argv:
        for index in dataframe.index:
            dataframe['Score'][index] = dataframe['Score'][index] + arg[index-1]
    return dataframe

In [18]:
zipcode = add_scores(zipcode, homicide_scores)

/Users/ncg/.local/share/virtualenvs/gvallocation-xprzTUHK/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [19]:
zipcode.to_csv('../app/resources/scores/zipcode_riskscores.csv')

In [20]:
zipcode_gdf = gpd.read_file('../app/resources/scores/zipcode_riskscores.csv')

In [21]:
zipcode_gdf = zipcode_gdf.drop(columns=['geometry', 'field_1'])

In [22]:
zipcode_gdf = zipcode_gdf.rename(columns={'SHAPES':'geometry'})

In [23]:
zipcode_gdf.head(3)

  ZIP_CD Homicides                                           geometry Score
0  60609      1136  MULTIPOLYGON (((-87.6266459027657 41.830905861...     4
1  60623      1122  MULTIPOLYGON (((-87.69479284658739 41.83007507...     4
2  60651      1087  MULTIPOLYGON (((-87.70655631674127 41.89555340...     4

In [27]:
zipcode_gdf.to_file('../app/resources/scores/zipcode_riskscores.geojson', driver='GeoJSON')

AttributeError: 'str' object has no attribute '__geo_interface__'